services:
  - type: web
    name: benefitspecs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

